### ISSUE TITLE
Nicht möglich beim Finanzierungspanel "Bestehendes Immobiliendarlehen hinzufügen"

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#20]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Betroffene Resource

01921e16-6a32-72ec-b2b4-30a058d31617

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

Ich hatte bereits des Öfteren angemerkt, dass wir vom Finanzierungspanel beim Kunden in einer bestehenden Immobilie kein Darlehen hinzufügen können. Wir können ein Darlehen erstellen und auch auf speichern klicken, aber es wird danach nicht angezeigt. Siehe Bild -> Ich hatte ein Darlehen angelegt und auf speichern geklickt aber trotzdem wird kein Darlehen angezeigt

### Erwartetes Verhalten

Nach speichern eines Darlehens müsste dieses auch angezeigt werden

### Wiederholt sich dieser Fehler?

Bereits mehrfach ausprobiert

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="1295" alt="Bildschirmfoto 2024-09-23 um 13 10 46" src="https://github.com/user-attachments/assets/89c6b1c1-8918-40b0-bebf-17004c89a546">

**Comment by john-wink** [comment]
Wenn du ein Kredit erstellst dann musst du die Seite 1x neuladen! Wenn du auf speichern klickst ohne die Seite vorher zu reloaden, Löscht sich das Vorhaben aus dem Repeater wieder.
