### ISSUE TITLE
Expose kann nicht erstellt werden

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#23]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Betroffene Resource

019237d3-5779-7125-b846-a43c9c6cf532/c9da1801-bd2a-4a6f-b79e-067f7b31da68/1ed765b8-0b78-47e3-b615-bcc6dd2c2ad6?expires=1735599599&signature=001568301de84aa96bd323150e8b0b360cec2d202f48c5278a84f52e447580f8

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

Es wird ein Link für das Expose erstellt. Allerdings steht dann nur "Hmmm...diese Seite ist leider nicht erreichbar"
https://[expose.finance-estate.art](https://expose.finance-estate.art/019237d3-5779-7125-b846-a43c9c6cf532/c9da1801-bd2a-4a6f-b79e-067f7b31da68/1ed765b8-0b78-47e3-b615-bcc6dd2c2ad6?expires=1735599599&signature=001568301de84aa96bd323150e8b0b360cec2d202f48c5278a84f52e447580f8)/019237d3-5779-7125-b846-a43c9c6cf532/c9da1801-bd2a-4a6f-b79e-067f7b31da68/1ed765b8-0b78-47e3-b615-bcc6dd2c2ad6?expires=1735599599&signature=001568301de84aa96bd323150e8b0b360cec2d202f48c5278a84f52e447580f8

### Erwartetes Verhalten

Link mit dem vorhandenen Expose

### Wiederholt sich dieser Fehler?

Bei mehreren Objekten ausprobiert

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="950" alt="Bildschirmfoto 2024-09-30 um 08 12 10" src="https://github.com/user-attachments/assets/58cd6dcf-6684-4e69-8a95-30266fdaf5c2">

**Comment by xibn** [comment]
@SophiaHintze der von dir bereitgestellte [Link des Exposés](https://expose.finance-estate.art/019237d3-5779-7125-b846-a43c9c6cf532/c9da1801-bd2a-4a6f-b79e-067f7b31da68/1ed765b8-0b78-47e3-b615-bcc6dd2c2ad6?expires=1735599599&signature=001568301de84aa96bd323150e8b0b360cec2d202f48c5278a84f52e447580f8) scheint wieder zu funktionieren. Der auf deinem Screenshot angezeigte Fehlercode `DNS_PROBE_FINISHED_NXDOMAIN` bedeutet wahrscheinlich, dass dein Computer den DNS-Record der `expose` Subdomain nicht finden konnte, weshalb die Website für dich nicht erreichbar war. Dies ist kein Fehler im CRM selbst und sollte sich eigentlich nach einer Weile von alleine beheben.

Falls der Fehler nicht verschwindet oder auf anderen Seiten/Subdomains ebenfalls auftaucht gerne ein neues Issue erstellen.
Ansonsten kannst du das Issue gerne schließen. 👍
