### ISSUE TITLE
Fehlermeldung beim Kunden während des Versuchs, den Finanzierer zu kontaktieren.

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#24]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [X] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [ ] Xcapital (Finanzierungsabteilung)

### Beschreibung

Der Kunde wollte uns über das Kundenpanel kontaktieren und erhielt dabei eine Fehlermeldung. Dadurch ging er davon aus, dass die Nachricht nicht versendet wurde, und versuchte es mehrfach erneut. Deshalb habe ich die Nachricht mehrfach erhalten. Der Versand hat zwar funktioniert, aber aufgrund der Fehlermeldung dachte der Kunde, dass es nicht geklappt hat.

### Erwartetes Verhalten

Eine Bestätigung, dass die Nachricht erfolgreich gesendet wurde.

### Wiederholt sich dieser Fehler?

Kunde hat es mehrfach probiert. 

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="480" alt="Bildschirmfoto 2024-10-01 um 13 33 13" src="https://github.com/user-attachments/assets/3e241cb7-a7de-447a-9cb9-6a0c6d65910b">

**Comment by xibn** [comment]
Der Bug wurde behoben und die neue Version sollte demnächst online sein. 👍
