### ISSUE TITLE
Wenn der Kunde über das Kundenprofil versucht den Finanzierer zu kontaktieren kommt eine Fehlermeldung

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#35]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [X] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [ ] Xcapital (Finanzierungsabteilung)

### Beschreibung

Wenn man über das Kundenpanel den Finanzierer kontaktieren möchte kommt die Fehlermeldung 500

### Erwartetes Verhalten

Info das die Nachricht versendet wurde. (Wenn der Kunde den Immobilienmakler kontaktieren möchte funktioniert der Prozess) 

### Wiederholt sich dieser Fehler?

Ja

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/bf3157e9-2ea9-4036-886a-6b7136101e41">

**Comment by SophiaHintze** [comment]
@john-wink Hi, funktioniert noch nicht

**Comment by john-wink** [comment]
Staging hat das deployment noch nicht funktioniert
