### ISSUE TITLE
Absprung ins Bankpanel funktioniert nicht

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#36]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Betroffene Resource

e176a783-21be-4427-a6ce-1c1e68f73dfe?expires=1728220785&signature=826330d151f0172a3f2188e87609b64d0abbfb0a9f37f2e6c0db2ff0b4e38b63

### Panels/ Team-Typ

- [X] Admin
- [X] Bank
- [ ] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [ ] Xcapital (Finanzierungsabteilung)

### Beschreibung

Der Absprung von Adimpanel ins Bankpanel funktioniert nicht

### Erwartetes Verhalten

Erfolgreicher Absprung ins Bankpanel

### Wiederholt sich dieser Fehler?

Ja

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="1292" alt="Bildschirmfoto 2024-10-06 um 15 15 14" src="https://github.com/user-attachments/assets/b32d47c5-7b12-464d-9f6b-a1c2f76eec2e">

<img width="1225" alt="Bildschirmfoto 2024-10-06 um 15 15 17" src="https://github.com/user-attachments/assets/d941ff0d-22a4-479b-accd-396c21f54a21">

**Comment by SophiaHintze** [comment]
@john-wink Hi, es funktioniert noch immer nicht

**Comment by john-wink** [comment]
Staging hat das deployment noch nicht funktioniert
