### ISSUE TITLE
Makler können auf "Bewilligt" drücken

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#41]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Betroffene Resource

2841daae-74ca-4ecf-ab75-6acdb01e8ba3

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [ ] Immo (Bauträger)
- [X] Makler
- [ ] Sales (Immobilienvertrieb)
- [ ] Xcapital (Finanzierungsabteilung)

### Beschreibung

Das Maklerpanel kann im Vorhaben wenn es bei der Bank liegt auf "Bewilligt" klicken und das Vorhaben geht dann zu den Darlehensverträgen. Kannst du mir die beiden Vorhaben von Schließleder wieder auf Bank schieben? Wir können dies nicht. 

### Erwartetes Verhalten

Der Makler sollte dies nicht können 

### Wiederholt sich dieser Fehler?

Ja

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

**Comment by john-wink** [comment]
Über "bearbeiten" könnt ihr die Phase immer noch ändern.
Die Rechteverwaltung ist noch nicht integriert, sobald diese integriert ist können wir das verschieben verhindern.
