### ISSUE TITLE
In der Suche werden „bestehende Immobilien" von Kunden angezeigt

### ISSUE THREAD

**Issue by chrisriefenstahl** [Estate-of-the-Art/finance-estate-issues#43]
### Eingeloggter Benutzer

christoffer.riefenstahl@xcapital.de

### Betroffene Resource

https://finanzierung.xcapital.de/x-capital-gmbh

### Panels/ Team-Typ

- [X] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [X] Immo (Bauträger)
- [X] Makler
- [X] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

In der Suche werden „bestehende Immobilien" von Kunden angezeigt. Es sollen aber keine Real Estates vom Typ „Bestehende Immobilien" angezeigt werden.

### Erwartetes Verhalten

Siehe oben

### Wiederholt sich dieser Fehler?

jap

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [X] den Fehler auf anderen Panels überprüft
- [X] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

![Bildschirmfoto 2024-10-29 um 00 19 29](https://github.com/user-attachments/assets/eac25e0b-f472-479a-989b-c09c6dd7d2ba)

**Comment by john-wink** [comment]
Das lässt sich nicht raus filtern weil Kunden auch RealEstates mit anderen Template Namen haben können
