### ISSUE TITLE
Der reservierte/platzierte Kunde ist auf dem Objekttyp „Mehrfamilienhaus (ungeteilt)" nicht sichtbar. Das Vorhaben fehlt beim Bauträger & Makler & Vertrieb, bei Admin & Finanzierung ist es sichtbar.

### ISSUE THREAD

**Issue by chrisriefenstahl** [Estate-of-the-Art/finance-estate-issues#44]
### Eingeloggter Benutzer

s.meyer@investo21.de

### Betroffene Resource

https://immo.finance-estate.art/investo21-grundbesitz/real-estates/01929975-cb2f-7092-a010-ad84528929f0

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [X] Immo (Bauträger)
- [X] Makler
- [X] Sales (Immobilienvertrieb)
- [ ] Xcapital (Finanzierungsabteilung)

### Beschreibung

Der reservierte/platzierte Kunde ist auf dem Objekttyp „Mehrfamilienhaus (ungeteilt)" nicht sichtbar. Das Vorhaben fehlt beim Bauträger & Makler & Vertrieb, bei Admin & Finanzierung ist es sichtbar.

### Erwartetes Verhalten

siehe oben

### Wiederholt sich dieser Fehler?

https://makler.finance-estate.art/marcus-skala-ps-immokonzepte/real-estate/shared/01929975-cb2f-7092-a010-ad84528929f0

### Operating System

- [X] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [X] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [X] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [X] den Fehler auf anderen Panels überprüft
- [X] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="1508" alt="1" src="https://github.com/user-attachments/assets/1241e28e-075a-4513-b5ae-8ca55ca88908">
<img width="1512" alt="fehlt Bauträger" src="https://github.com/user-attachments/assets/0c4594f2-0a55-46f3-a9cc-1236281d5a0c">
<img width="1509" alt="fehlt Makler" src="https://github.com/user-attachments/assets/c38d7e72-d0c9-4082-9c32-6d59fbe390c8">

**Comment by john-wink** [comment]
Ist kein Bug/Fehler.
Ist ein Featurewunsch.
Zur Roadmap hinzufügen und einordnen.

**Comment by john-wink** [comment]
@maxibue kannst du das aus Admin oder Finanzierung zu den anderen Panels kopieren und zu allen 3 Branches pushen?
