### ISSUE TITLE
Falsche Farbe bei der Timeline, wenn ein Vorhaben auf verloren gesetzt wird

### ISSUE THREAD

**Issue by Jessica-varkentin** [Estate-of-the-Art/finance-estate-issues#46]
### Panels/ Team-Typ

- [X] Admin
- [X] Bank
- [X] Customer (Kunde)
- [X] Immo (Bauträger)
- [X] Makler
- [X] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

Wenn man ein Vorhaben auf verloren setzt, wird die Timeline grün.

### Erwartetes Verhalten

Die Timeline sollte rot werden, wenn man ein Vorhaben auf verloren setzt

### Wiederholt sich dieser Fehler?

Ja

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

![Bildschirmfoto 2024-11-08 um 16 00 06](https://github.com/user-attachments/assets/06008b24-abcc-4517-a5ff-09d44bd1a00c)

**Comment by john-wink** [comment]
Diese Farbe lässt sich nicht ändern und ist immer grün. Abhängig auf welcher Phase man sich gerade befindet, wenn die Phase noch nicht erreich ist, ist die Phase ausgegraut.
