### ISSUE TITLE
Checkliste Kategorie letzte Bezügemitteilung rot, obwohl kategorisiert

### ISSUE THREAD

**Issue by KarinSchr** [Estate-of-the-Art/finance-estate-issues#52]
### Eingeloggter Benutzer

karin.schroder@xcapital.de

### Betroffene Resource

0193696e-7367-7280-bf9f-482c97d27d29/edit

### Panels/ Team-Typ

- [X] Admin
- [X] Bank
- [X] Customer (Kunde)
- [X] Immo (Bauträger)
- [X] Makler
- [X] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

die Kategorie "letzte Bezügemitteilung" bleibt nach Upload des Dokumentes und kategorisierung dennoch rot, auch wenn man die Katgeorie geprüft hat

### Erwartetes Verhalten

Statdessen hätte "letzte Bezügemitteilung" in der Checkliste Orange oder grün werden müssen

### Wiederholt sich dieser Fehler?

ja, ein Dokument als "letzte Bezügemitteilung" kategorisieren
<img width="1488" alt="Bildschirmfoto 2024-12-06 um 16 35 07" src="https://github.com/user-attachments/assets/50bc9d58-4ab9-4219-a7c4-35e803d514e9">
<img width="1496" alt="Bildschirmfoto 2024-12-06 um 15 02 46" src="https://github.com/user-attachments/assets/b76d4c7e-e6c8-4db8-a34e-27c8a9205ff4">

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [X] den Fehler auf anderen Panels überprüft
- [X] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

**Comment by john-wink** [comment]
Das wird irgendwo ein Fehler sein bei den selects. 
Da kann ich leider nichts programmieren m.
Dafür bitte an Chris wenden.
